language: 'python'
python:
  - '2.7'
install:
  - 'pip install -r requirements.txt'
  - './scripts/server-setup.sh -t'
before_script:
  - "psql -c 'create database travis_ci_test;' -U postgres"
  - 'python manage.py syncdb'
script:
  - 'python manage.py test'