language: 'python'
sudo: false
branches:
  only:
    - development_3k
python:
  - '3.4'
before_install:
  - 'pip install -r travis-requirements.txt'
install:
  - 'pip install -r requirements.txt'
  - './scripts/server-setup.sh -t'
before_script:
  - "psql -c 'create database satnet_db;' -U postgres"
  - 'python manage.py migrate'
script:
  - 'coverage erase'
  - 'coverage run manage.py test --with-coverage'
after_success:
  - 'coverage combine'
  - "coverage report --omit '/home/travis/virtualenv/*'"
  - 'coveralls'