language: 'python'
branches:
  only:
    - development_3k
python:
  - '3.4'
before_install:
  - 'pip install codecov'
  - 'pip install codacy-coverage'
install:
  - 'pip install -r requirements.txt'
  - './scripts/server-setup.sh -t'
before_script:
  - "psql -c 'create database satnet_db;' -U postgres"
  - 'python manage.py migrate'
script:
  - 'python manage.py test --with-coverage'
after_success:
  - 'codecov'
  - "export CODACY_PROJECT_TOKEN='daad0cf71b914bb38396a4efc9c2c490'"
  - 'python-codacy-coverage -r coverage.xml'

# old coveralls.io method
#  - 'coverage erase'
#  - 'coverage run manage.py test'
# after_script:
#  - 'coveralls'
