language: 'python'
python:
  - '3.4'
install:
  - 'pip install -r requirements.txt'
  - './scripts/server-setup.sh -t'
before_script:
  - "psql -c 'create database satnet_db;' -U postgres"
  - 'python manage.py migrate'
script:
  - 'python manage.py test'