language: 'python'
branches:
  only:
    - development_3k
python:
  - '3.4'
before_install:
  - 'pip install beautifulsoup4'
  - 'pip install coverage'
  - 'pip install coverage-reporter'
  - 'pip install python-coveralls'
  - 'pip install lxml'
  # - 'pip install codacy-coverage'
  # - 'pip install codecov'
  # - 'pip install coveralls'
install:
  - 'pip install -r requirements.txt'
  - './scripts/server-setup.sh -t'
before_script:
  - "psql -c 'create database satnet_db;' -U postgres"
  - 'python manage.py migrate'
script:
  # - 'coverage erase'
  - 'coverage run manage.py test'
after_success:
  # - 'codecov'
  # - "export CODACY_PROJECT_TOKEN='daad0cf71b914bb38396a4efc9c2c490'"
  # - 'python-codacy-coverage -r coverage.xml'
  # - 'coverage run manage.py test'
  - 'coveralls'