language: 'python'
python:
  - '2.7'
install:
  - 'pip install .'
  - 'pip install -r requirements.txt'
  - './scripts/server-setup.sh -t'
before_script:
  - 'python manage.py syncdb'
script:
  - 'python manage.py test'